// projects/blog-h5/src/components/expandable-content.tsx
import { useState } from 'react'
interface Props {
  content: string
  maxLength?: number
  maxLine?: number
  expandText?: string
  collapseText?: string
}

export default function ExpandableContent({
  content,
  maxLine = 3,
  maxLength = 180,
  expandText = '展开',
  collapseText = '收起'
}: Props) {
  const [isExpanded, setIsExpanded] = useState(false)
  let showAction = false
  let isMultiLine = false
  let expandBtnText = expandText
  let collapseBtnText = collapseText
  let briefContent = content

  const lineList = content.split('\n')
  if (lineList.length > maxLine) {
    briefContent = lineList.slice(0, maxLine).join('\n') + '\n...'
    expandBtnText = '\n' + expandText
    collapseBtnText = '\n' + collapseText
    showAction = true
    isMultiLine = true
  } else if (content.length > maxLength) {
    briefContent = content.slice(0, maxLength) + '...'
    showAction = true
  }

  function triggleExpand() {
    setIsExpanded((v) => !v)
  }

  return (
    <div className="whitespace-pre-wrap break-words transition-all">
      {isExpanded ? content : briefContent}
      {showAction && (
        <span
          className={`text-green-700 ${isMultiLine ? '' : 'ml-1'}`}
          onClick={triggleExpand}
        >
          {isExpanded ? collapseBtnText : expandBtnText}
        </span>
      )}
    </div>
  )
}

// projects/blog-nuxt3/components/ExpandableContent.vue
<template>
  <div class="whitespace-pre-wrap break-words transition-all">
    {{ isExpanded ? content : getPostSummary(content) }}
    <n-button text type="primary" @click="isExpanded = !isExpanded" v-if="content?.length > maxLength">{{ isExpanded ? '收起' : '展开' }}</n-button>
  </div>
</template>

<script setup lang="ts">
import { NButton } from "naive-ui"
interface Props{
  content: string
  maxLength?: number
}

const props = withDefaults(defineProps<Props>(), {
  maxLength: 280
})
const isExpanded = ref(false)

function getPostSummary(content: string) {
  if(content && content.length > props.maxLength){
    return content.slice(0, props.maxLength) + '...'
  }else{
    return content
  }
}
</script>
