// projects/blog-h5/src/components/comment/comment-item.tsx
import { Comment } from 'sys-types'
import UserAvatar from '@/components/user/user-avatar'
import UserName from '@/components/user/user-name'
import ExpandableContent from '@/components/expandable-content'
import MediaImageItem from '@/components/media/media-image-item'
import YTime from '@/components/y-time'
import { Space } from 'react-vant'
import CommentActions from '@/components/comment/comment-actions'
import CommentReply from '@/components/comment/comment-reply'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowDown } from '@react-vant/icons'

interface Props {
  comment: Comment
  className?: string
  onDelete?: () => void
  onReply: () => void
}
export default function CommentItem({
  comment,
  className,
  onDelete,
  onReply
}: Props) {
  const [showReply, setShowReply] = useState(false)
  const navigate = useNavigate()

  return (
    <div className={`comment-item flex flex-col items-start py-3 ${className}`}>
      <div className="flex items-center gap-2">
        <UserAvatar user={comment.createBy} />
        <UserName user={comment.createBy} />
      </div>
      <div className="w-full" onClick={() => setShowReply(true)}>
        <div className="my-1 inline w-full whitespace-pre-wrap break-words">
          {comment.replyComment && comment.replyComment.topCommentId ? (
            <>
              <span>回复</span>
              <UserName user={comment.replyComment.createBy} showAt />
              <span className="mr-[2px]">:</span>
            </>
          ) : null}
          <ExpandableContent
            className="inline"
            content={comment.content || '图片评论'}
            maxLength={60}
          />
        </div>
        {comment.image && (
          <MediaImageItem
            className="max-h-[160px] max-w-[120px]"
            url={comment.image.url}
          />
        )}
      </div>
      <div className="mt-1 flex w-full justify-between">
        <YTime time={comment.createdAt}></YTime>
        <CommentActions comment={comment} onDelete={onDelete} />
      </div>

      {comment.childComments?.length ? (
        <div
          className="bg-block-section mt-2 min-w-full rounded px-2 py-1"
          onClick={() => navigate('/commentDetail/' + comment.id)}
        >
          <Space direction="vertical" gap={4}>
            {comment.childComments.map((child) => (
              <div className="whitespace-pre-wrap break-words" key={child.id}>
                <UserName user={child.createBy} showAt />
                {child.replyComment?.topCommentId && (
                  <>
                    <span className="mx-[2px]">回复</span>
                    <UserName user={child.replyComment.createBy} showAt />
                  </>
                )}
                <span className="ml-[2px] mr-[4px]">:</span>
                {child.content ? (
                  <ExpandableContent
                    className="my-1 inline"
                    imageUrl={child.image?.url}
                    content={child.content}
                    maxLength={60}
                  />
                ) : null}
              </div>
            ))}
            {comment.childCommentsCount > 2 ? (
              <div className="flex items-center gap-[2px] text-primary">
                <span>共 {comment.childCommentsCount} 条回复</span>
                <ArrowDown />
              </div>
            ) : null}
          </Space>
        </div>
      ) : (
        ''
      )}

      <CommentReply
        visible={showReply}
        onClickOverlay={() => setShowReply(false)}
        comment={comment}
        onComplete={() => {
          onReply()
          setShowReply(false)
        }}
        postId={comment.blogId as number}
      />
    </div>
  )
}

// projects/blog-uni/pages/post/components/comment-item.vue
<template>
	<view class="comment-item">
		<view class="comment-left">
			<UserAvatar :user="comment.createBy" :size="48"></UserAvatar>
		</view>
		<view class="comment-right" @click.stop="$emit('showReply', comment)">
			<view class="user-name text-ellipsis">
				{{ comment.createBy.name }}
			</view>
			<YExpandanleContent :maxLength="120" :content="comment.content"></YExpandanleContent>
			<view class="comment-bottom">
				<YTime class="item-time" type="format" :time="comment.createdAt"></YTime>
			</view>
			<view class="comment-reply-container" v-if="comment.childComments.length">
				<view class="reply-item" v-for="reply in comment.childComments" :key="reply.id"
					@click.stop="$emit('showReply', reply)">
					<UserName :user="reply.createBy" :text="'@' + reply.createBy.name"></UserName>{{ reply.replyComment && reply.replyComment.topCommentId ? '' : ':'}}
					<view class="at-user-contsiner" v-if="reply.replyComment && reply.replyComment.topCommentId">
						回复<UserName :user="reply.replyComment.createBy" :text="'@' + reply.replyComment.createBy.name"></UserName>:
					</view>
					<view class="reply-content">
						<YExpandanleContent :maxLength="120" :content="reply.content"></YExpandanleContent>
					</view>
				</view>
				<view class="more-action-container" v-if="comment.childCommentsCount > 2"
					@click.stop="handleViewAllReply">
					<view>共{{ comment.childCommentsCount }}条回复</view>
					<uni-icons type="bottom" size="18" color="#18a058"></uni-icons>
				</view>
			</view>
		</view>
	</view>
</template>

<script>
	import YExpandanleContent from '@/components/y-expandable-content.vue'
	import YTime from '@/components/y-time.vue'
	export default {
		name: 'comment-item',
		props: {
			comment: Object
		},
		emits: ['showReply'],
		components: {
			YExpandanleContent,
			YTime,
		},
		data() {
			return {

			}
		},
		methods: {
			handleViewAllReply() {
				uni.navigateTo({
					url: `/pages/comment-detail/comment-detail?id=${this.comment.id}&blogId=${this.comment.blogId}`
				})
			}
		}
	}
</script>

<style lang="scss" scoped>
	.comment-item {
		display: flex;
		align-items: flex-start;
		gap: 20rpx;
	}

	.comment-right {
		display: flex;
		flex-direction: column;
		align-items: flex-start;
		gap: 8rpx;
		flex: 1;

		.user-name {
			font-size: 16px;
			color: $uni-primary;
			font-weight: 600;
		}

		.comment-bottom {
			display: flex;
			align-items: center;
			justify-content: flex-start;
			gap: 8rpx;

			.item-time {
				color: $uni-secondary-color;
				font-size: 14px;
			}
		}
	}

	.comment-reply-container {
		border-radius: 6rpx;
		background-color: $uni-bg-color;
		padding: 26rpx;
		width: 100%;
		box-sizing: border-box;

		.reply-item {
			word-wrap: break-word;
			word-break: break-word;
			white-space: pre-wrap;

			.reply-user {
				color: $uni-primary;
				font-weight: 600;
			}

			.at-user-contsiner {
				display: inline;

				.at-user {
					margin: 0 2rpx;
					color: $uni-primary;
					font-weight: 600;
					display: inline;
				}
			}

			.reply-content {
				margin-left: 10rpx;
				display: inline;
			}
		}

		.more-action-container {
			color: $uni-primary;
			margin-top: 8rpx;
			font-size: 16px;
			display: flex;
			align-items: center;
			gap: 10rpx;
		}
	}
</style>
