// projects/blog-nuxt3/components/Media/MediaVideoItem.vue
<template>
  <div class="w-full">
    <div class="w-full video-item-container">
      <video
        ref="videoRef"
        class="video-item"
        controls
        :src="config.imageBase + url"
      ></video>
      <template v-if="coverUrl && playState === PlayState.idle">
        <MediaImgView class="video-cover" :url="coverUrl" />
        <n-icon
          size="72"
          class="play-icon"
          :component="PlayCircle24Regular"
          @click="handlePlay"
        />
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { NIcon } from 'naive-ui'
import { PlayCircle24Regular } from '@vicons/fluent'
import { PlayState } from 'sys-types'

interface Props {
  url: string
  coverUrl?: string
}

const props = defineProps<Props>()
const config = useRuntimeConfig()
const videoRef = ref<HTMLVideoElement>()
const playState = ref<PlayState>(PlayState.idle)

function handlePlay() {
  playState.value = PlayState.playing
  videoRef.value.play()
}
</script>

<style scoped lang="scss">
.video-item-container {
  @apply relative w-full h-0;
  padding-top: 56.25%;
  border-radius: 5px;
  .video-item {
    @apply w-full h-full object-contain overflow-clip absolute top-0 cursor-pointer bg-black;
    border-radius: inherit; // 图片圆角
  }
  .video-cover {
    @apply absolute object-cover overflow-clip top-0 w-full h-full;
    border-radius: inherit;
  }
  .play-icon {
    @apply cursor-pointer z-10 absolute top-1/2 left-1/2 text-white;
    transform: translate(-50%, -50%);
  }
}
</style>

// projects/blog-h5/src/components/media/media-video-item.tsx
import MediaImageItem from '@/components/media/media-image-item'
import { PlayCircle } from '@react-vant/icons'
import React, { useRef } from 'react'
import { useState, useEffect } from 'react'

interface Props {
  url: string
  coverUrl?: string
}

export default function MediaVideoItem({ url, coverUrl }: Props) {
  const [isPlaying, setIsPlaying] = useState(false)
  const videoRef = useRef<HTMLVideoElement>(null)

  function playVideo() {
    console.log('==================')
    videoRef.current?.play()
    setIsPlaying(true)
  }

  const base: string = import.meta.env.VITE_IMAGE_BASE
  return (
    <div className="media-video-item w-full h-full">
      <div
        className="relative w-full h-0 bg-black"
        style={{ paddingTop: 'calc(100% * 9 / 16)' }}
      >
        <video
          className="absolute w-full h-full top-0"
          controls
          preload="auto"
          src={base + url}
          ref={videoRef}
        ></video>
        {coverUrl && !isPlaying && (
          <div onClick={playVideo}>
            <MediaImageItem
              url={coverUrl}
              quality={60}
              className="absolute object-cover overflow-clip top-0 w-full h-full"
            />
            <PlayCircle
              className="z-2 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
              color="#fff"
              fontSize="56px"
            />
          </div>
        )}
      </div>
    </div>
  )
}
