// projects/blog-nuxt3/src/components/Media/MediaAudioItem.vue
<template>
  <div class="media-audio-item">
    <audio
      ref="audioRef"
      class="hidden"
      :src="audioSrc"
      @pause="
        () => {
          playState = PlayState.paused
        }
      "
      @ended="handlePlayEnd"
      @loadedmetadata="handleGetDuration"
      @timeupdate="handleTimeUpdate"
    />
    <div v-if="coverUrl" class="w-1/3">
      <div
        class="relative h-0 w-full rounded-[15px] bg-black"
        :style="{ 'padding-top': 'calc(100%*9/16)' }"
      >
        <MediaImgView v-if="coverUrl" class="media-cover" :url="coverUrl" />
        <div
          class="transform-center z-10 flex flex-col items-center justify-center text-white"
        >
          <div class="cursor-pointer">
            <Icon
              v-if="playState === PlayState.playing"
              name="fluent:pause-circle-20-regular"
              size="48"
              @click="handlePlay"
            />
            <Icon
              v-else-if="playState === PlayState.end"
              name="fluent:replay-20-regular"
              size="48"
              @click="handlePlay"
            />
            <Icon
              v-else
              name="fluent:play-circle-16-regular"
              size="48"
              @click="handlePlay"
            />
          </div>
          <span
            >{{ currentTime > 0 ? `${formatDuration(currentTime)} | ` : '' }}
            {{ formatDuration(duration) }}</span
          >
        </div>
        <span
          class="media-tag absolute right-0 top-0 rounded-bl-[3px] rounded-tr-[3px]"
          >录音</span
        >
      </div>
    </div>

    <div
      v-else-if="duration"
      class="flex w-fit items-center rounded-[6px] bg-gray-200 px-[12px] py-[5px] dark:bg-gray-600"
    >
      <div class="flex cursor-pointer items-center">
        <Icon
          v-if="playState === PlayState.playing"
          name="fluent:pause-circle-20-regular"
          size="24"
          @click="handlePlay"
        />
        <Icon
          v-else-if="playState === PlayState.end"
          name="fluent:replay-20-regular"
          size="24"
          @click="handlePlay"
        />
        <Icon
          v-else
          name="fluent:play-circle-16-regular"
          size="24"
          @click="handlePlay"
        />
      </div>
      <div class="divide-x divide-gray-400">
        <span class="px-[8px]">{{ formatDuration(currentTime) }}</span>
        <span class="px-[8px]">{{ formatDuration(duration) }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { PlayState, formatDuration } from 'sys-types'
import { useMediaPlayStore } from '~/store/modules/mediaPlayStore'

interface Props {
  url: string
  isAbsoluteUrl?: boolean
  coverUrl?: string
}

const playStore = useMediaPlayStore()
const config = useRuntimeConfig()
const props = withDefaults(defineProps<Props>(), {
  isAbsoluteUrl: false
})
const audioRef = ref<HTMLAudioElement>()
const playState = ref<PlayState>(PlayState.idle)
const duration = ref(0)
const isInfinityDuration = ref(false)
const currentTime = ref(0)

const audioSrc = computed(() => {
  let result = ''
  if (props.isAbsoluteUrl) {
    result = props.url
  } else {
    result = config.public.imageBase + props.url
  }
  if (!result.startsWith('blob:')) {
    result += '?type=audio'
  }
  return result
})

onMounted(() => {
  handleGetDuration()
})

function handlePlay() {
  playStore.currentRef?.pause()
  playStore.currentRef = audioRef.value
  if (playState.value === PlayState.playing) {
    audioRef.value?.pause()
    playState.value = PlayState.paused
  } else {
    audioRef.value?.play()
    playState.value = PlayState.playing
  }
}

function handleGetDuration() {
  duration.value = audioRef.value?.duration
  handleUnknownDuration()
}

function handleTimeUpdate() {
  // console.log(
  //   '======handleTimeUpdate=====',
  //   duration.value,
  //   audioRef.value?.currentTime,
  //   audioRef.value?.duration
  // )
  currentTime.value = audioRef.value?.currentTime || 0
  duration.value = audioRef.value?.duration
  // 获取时长时设置了超长播放时间而触发 end 事件
  if (isInfinityDuration.value) {
    audioRef.value.currentTime = 0
    isInfinityDuration.value = false
    playState.value = PlayState.idle
  }
}

function handlePlayEnd() {
  playState.value = PlayState.end
  // console.log('======handlePlayEnd=====', audioRef.value.currentTime)
}

// chrome 获取的时长可能是Infinity，需要这样处理
function handleUnknownDuration() {
  // console.log('======handleUnknownDuration=====', props.url, duration.value)
  if (
    audioRef.value &&
    (duration.value === Infinity || isNaN(Number(duration.value)))
  ) {
    isInfinityDuration.value = true
    audioRef.value.currentTime = 1e101 // 设置一个极大的时间，能显示后再在 handleTimeUpdate 设置回开始
  }
}
</script>

<style scoped lang="postcss">
.media-cover {
  @apply absolute top-0 h-full w-full overflow-clip object-cover;
  border-radius: inherit;
}
</style>

// projects/blog-h5/src/components/media/media-audio-item.tsx
import MediaImageItem from '@/components/media/media-image-item'
import { PlayCircle, PauseCircle, Replay, Play, Pause } from '@react-vant/icons'
import React, { useRef, useState } from 'react'

import { PlayState, timeUtils } from 'sys-types'

interface Props {
  url: string
  isAbsoluteUrl?: boolean
  coverUrl?: string
}

export default function MediaAudioItem({
  url,
  coverUrl,
  isAbsoluteUrl = false
}: Props) {
  const [playState, setPlayState] = useState<PlayState>(PlayState.idle)
  const audioRef = useRef<HTMLAudioElement>(null)
  const [duration, setDuration] = useState(0)
  const [currentTime, setCurrentTime] = useState(0)

  function playVideo(e: any) {
    e.stopPropagation()
    if (playState === PlayState.playing) {
      audioRef.current?.pause()
      setPlayState(PlayState.paused)
    } else {
      audioRef.current?.play()
      setPlayState(PlayState.playing)
    }
  }

  const base: string = import.meta.env.VITE_IMAGE_BASE

  const player = (
    <audio
      preload="auto"
      src={isAbsoluteUrl ? url : base + url}
      ref={audioRef}
      onEnded={() => setPlayState(PlayState.end)}
      onDurationChange={() => setDuration(audioRef.current?.duration || 0)}
      onTimeUpdate={() => setCurrentTime(audioRef.current?.currentTime || 0)}
    ></audio>
  )

  const smallPlayer = (
    <div>
      {player}
      <div className="flex w-fit items-center gap-[4px] rounded-[5px] bg-gray-200 px-[8px] py-[5px] dark:bg-gray-600">
        <div>
          {playState === PlayState.playing && (
            <Pause fontSize="18px" onClick={playVideo} />
          )}
          {[PlayState.idle, PlayState.paused].includes(playState) && (
            <Play fontSize="18px" onClick={playVideo} />
          )}
          {playState === PlayState.end && (
            <Replay fontSize="18px" onClick={playVideo} />
          )}
        </div>
        <div className="divide-x divide-gray-400 text-[12px]">
          <span className="px-[8px]">
            {timeUtils.formatDuration(currentTime || 0)}
          </span>
          <span className="px-[8px]">{timeUtils.formatDuration(duration)}</span>
        </div>
      </div>
    </div>
  )

  const largePlayer = (
    <div className="media-video-item h-full w-full">
      <div
        className="relative h-0 w-full bg-black"
        style={{ paddingTop: 'calc(100% * 9 / 16)' }}
      >
        {player}

        {coverUrl && (
          <div onClick={playVideo}>
            <MediaImageItem
              url={coverUrl}
              quality={60}
              className="absolute top-0 h-full w-full overflow-clip object-cover"
            />
            <div className="z-2 absolute left-1/2 top-1/2 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center text-white">
              {playState === PlayState.playing && (
                <PauseCircle fontSize="56px" onClick={playVideo} />
              )}
              {[PlayState.idle, PlayState.paused].includes(playState) && (
                <PlayCircle fontSize="56px" onClick={playVideo} />
              )}
              {playState === PlayState.end && (
                <Replay fontSize="56px" onClick={playVideo} />
              )}
              {duration > 0 && (
                <h3 className="text-center">
                  {currentTime > 0
                    ? `${timeUtils.formatDuration(currentTime)}/`
                    : ''}
                  {timeUtils.formatDuration(duration)}
                </h3>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  )

  return coverUrl ? largePlayer : smallPlayer
}
