// projects/blog-react-h5/src/components/media/media-audio-item.tsx
import MediaImageItem from '@/components/media/media-image-item'
import { PlayCircle, PauseCircle, Replay, Play, Pause } from '@react-vant/icons'
import React, { useRef } from 'react'
import { useState } from 'react'
import TimeUtils from '@/utils/timeUtils'

interface Props {
  url: string
  coverUrl?: string
}

enum PlayState {
  idle,
  playing,
  paused,
  end
}

export default function MediaAudioItem({ url, coverUrl }: Props) {
  const [playState, setPlayState] = useState<PlayState>(PlayState.idle)
  const audioRef = useRef<HTMLAudioElement>(null)
  const [duration, setDuration] = useState(0)
  const [currentTime, setCurrentTime] = useState(0)

  function playVideo() {
    if (playState === PlayState.playing) {
      audioRef.current?.pause()
      setPlayState(PlayState.paused)
    } else {
      audioRef.current?.play()
      setPlayState(PlayState.playing)
    }
  }

  const base: string = import.meta.env.VITE_IMAGE_BASE

  const player = (
    <audio
      preload="auto"
      src={base + url}
      ref={audioRef}
      onEnded={() => setPlayState(PlayState.end)}
      onDurationChange={() => setDuration(audioRef.current?.duration || 0)}
      onTimeUpdate={() => setCurrentTime(audioRef.current?.currentTime || 0)}
    ></audio>
  )

  const smallPlayer = (
    <div>
      {player}
      <div className="flex items-center gap-[4px] text-gray-700 bg-gray-200 rounded-[5px] py-[5px] px-[12px]">
        <h3 className="text-start flex-1">
          {TimeUtils.formatDuration(currentTime || 0)}
        </h3>
        <div>
          {playState === PlayState.playing && (
            <Pause fontSize="20px" onClick={playVideo} />
          )}
          {[PlayState.idle, PlayState.paused].includes(playState) && (
            <Play fontSize="20px" onClick={playVideo} />
          )}
          {playState === PlayState.end && (
            <Replay fontSize="20px" onClick={playVideo} />
          )}
        </div>
        <h3 className="text-end flex-1">
          {TimeUtils.formatDuration(duration)}
        </h3>
      </div>
    </div>
  )

  const largePlayer = (
    <div className="media-video-item w-full h-full">
      <div
        className="relative w-full h-0 bg-black"
        style={{ paddingTop: 'calc(100% * 9 / 16)' }}
      >
        {player}

        {coverUrl && (
          <div onClick={playVideo}>
            <MediaImageItem
              url={coverUrl}
              quality={60}
              className="absolute object-cover overflow-clip top-0 w-full h-full"
            />
            <div className="z-2 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-white flex flex-col items-center">
              {playState === PlayState.playing && (
                <PauseCircle fontSize="56px" onClick={playVideo} />
              )}
              {[PlayState.idle, PlayState.paused].includes(playState) && (
                <PlayCircle fontSize="56px" onClick={playVideo} />
              )}
              {playState === PlayState.end && (
                <Replay fontSize="56px" onClick={playVideo} />
              )}
              {duration > 0 && (
                <h3 className="text-center">
                  {currentTime > 0
                    ? `${TimeUtils.formatDuration(currentTime)}/`
                    : ''}
                  {TimeUtils.formatDuration(duration)}
                </h3>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  )

  return coverUrl ? largePlayer : smallPlayer
}

// projects/blog-nuxt3/components/Media/MediaAudioItem.vue
<template>
  <div class="media-audio-item">
    <audio
      class="hidden"
      :src="config.imageBase + url"
      ref="audioRef"
      @ended="
        () => {
          playState = PlayState.end
        }
      "
      @durationchange="
        () => {
          duration = audioRef?.duration || 0
        }
      "
      @timeupdate="
        () => {
          currentTime = audioRef?.currentTime || 0
        }
      "
    ></audio>
    <div class="w-1/3" v-if="coverUrl">
      <div
        class="w-full h-0 relative bg-black rounded-[3px]"
        :style="{ 'padding-top': 'calc(100%*9/16)' }"
      >
        <MediaImgView class="media-cover" :url="coverUrl" v-if="coverUrl" />
        <div
          class="flex flex-col justify-center items-center gap-[5px] text-white transform-center"
        >
          <n-icon
            size="48"
            :component="PauseCircle24Regular"
            @click="handlePlay"
            v-if="playState === PlayState.playing"
          />
          <n-icon
            size="48"
            :component="Replay20Regular"
            @click="handlePlay"
            v-else-if="playState === PlayState.end"
          />
          <n-icon
            size="48"
            :component="PlayCircle24Regular"
            @click="handlePlay"
            v-else
          />
          <span
            >{{ currentTime > 0 ? `${formatDuration(currentTime)}/` : '' }}
            {{ formatDuration(duration) }}</span
          >
        </div>
      </div>
    </div>
    <div
      class="w-fit flex items-center px-[12px] py-[5px] dark:bg-gray-600 bg-gray-200 rounded-[6px]"
      v-else-if="duration"
    >
      <div class="flex items-center">
        <n-icon
          size="24"
          :component="PauseCircle24Regular"
          @click="handlePlay"
          v-if="playState === PlayState.playing"
        />
        <n-icon
          size="24"
          :component="Replay20Regular"
          @click="handlePlay"
          v-else-if="playState === PlayState.end"
        />
        <n-icon
          size="24"
          :component="PlayCircle24Regular"
          @click="handlePlay"
          v-else
        />
      </div>
      <div class="divide-x divide-gray-400">
        <span class="px-[8px]">{{ formatDuration(currentTime) }}</span>
        <span class="px-[8px]">{{ formatDuration(duration) }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { NIcon } from 'naive-ui'
import {
  PlayCircle24Regular,
  PauseCircle24Regular,
  Replay20Regular
} from '@vicons/fluent'
import { PlayState } from 'sys-types'

interface Props {
  url: string
  coverUrl?: string
}

const config = useRuntimeConfig()
const props = defineProps<Props>()
const audioRef = ref<HTMLAudioElement>()
const playState = ref<PlayState>(PlayState.idle)
const duration = ref(0)
const currentTime = ref(0)

function handlePlay() {
  if (playState.value === PlayState.playing) {
    audioRef.value?.pause()
    playState.value = PlayState.paused
  } else {
    audioRef.value?.play()
    playState.value = PlayState.playing
  }
}
</script>

<style scoped lang="scss">
.media-cover {
  @apply absolute object-cover overflow-clip top-0 w-full h-full;
  border-radius: inherit;
}
.transform-center {
  @apply cursor-pointer z-10 absolute top-1/2 left-1/2;
  transform: translate(-50%, -50%);
}
</style>
