// projects/blog-nuxt3/components/user/UserName.vue
<template>
  <span
    class="cursor-pointer text-green-700"
    @click="navigateTo({ path: '/user/' + user.id })"
  >
    {{ (showAt ? '@' : '') + user.name }}
  </span>
</template>

<script setup lang="ts">
import { User } from 'sys-types'

interface Props {
  user: User
  showAt?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  showAt: false
})
</script>

// projects/blog-h5/src/components/user/user-name.tsx
import { User } from 'sys-types'

interface Props {
  user: User
  showAt?: boolean
}
export default function UserName({ user, showAt = false }: Props) {
  return (
    <span className="user-name whitespace-pre-wrap break-words text-green-700">
      {(showAt ? '@' : '') + user.name}
    </span>
  )
}
