// projects/blog-nuxt3/src/components/user/UserName.vue
<template>
  <UserCard :uid="user.id" :uname="user.name" :disabled="disabled">
    <template #trigger>
      <span
        class="cursor-pointer text-primary"
        @click="navigateTo({ path: '/user/id/' + user.id })"
      >
        {{ (showAt ? '@' : '') + user.name }}
      </span>
    </template>
  </UserCard>
</template>

<script setup lang="ts">
import type { User } from 'sys-types'

interface Props {
  user: User
  showAt?: boolean
  disabled?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  showAt: false,
  disabled: false
})
</script>

// projects/blog-h5/src/components/user/user-name.tsx
import { User } from 'sys-types'

interface Props {
  user: User
  showAt?: boolean
  className?: string
}
export default function UserName({ user, showAt = false, className }: Props) {
  return (
    <span
      className={`user-name whitespace-pre-wrap break-words text-primary ${
        className || ''
      }`}
    >
      {(showAt ? '@' : '') + user.name}
    </span>
  )
}
