// projects/blog-h5/src/components/post/post-item.tsx
import { Blog } from 'sys-types'
import UserAvatar from '@/components/user/user-avatar'
import UserName from '@/components/user/user-name'
import YTime from '@/components/y-time'
import MediaList from '@/components/media/media-list'
import YCard from '@/components/y-card'
import ExpandableContent from '@/components/expandable-content'
import { GoodJob, GoodJobO, StarO, Star, CommentO } from '@react-vant/icons'
import { useState } from 'react'
import $http, { blog_collect, blog_like } from '@/http'
import { Toast } from 'react-vant'
import { useNavigate } from 'react-router-dom'

interface Props {
  post: Blog
}
export default function PostItem({ post }: Props) {
  const [postDetail, setPostDetail] = useState<Blog>(post)
  const navigate = useNavigate()

  async function handleLike() {
    try {
      const { msg, success, result } = await $http.post(blog_like, {
        id: postDetail.id,
        isLike: postDetail.isLike ? 0 : 1
      })
      if (success) {
        setPostDetail((post) => ({
          ...post,
          isLike: !post.isLike,
          likedByCount: postDetail.isLike
            ? post.likedByCount! - 1
            : post.likedByCount! + 1
        }))
      } else {
        Toast.fail(msg || '点赞失败')
      }
    } catch (e) {
      Toast.fail('点赞失败')
      console.log('=====handleLike error======', e)
    }
  }

  async function handleCollect() {
    try {
      const { msg, success, result } = await $http.post(blog_collect, {
        id: postDetail.id,
        isCollect: postDetail.isCollect ? 0 : 1
      })
      if (success) {
        setPostDetail((post) => ({
          ...post,
          isCollect: !post.isCollect,
          collectedByCount: postDetail.isCollect
            ? post.collectedByCount! - 1
            : post.collectedByCount! + 1
        }))
      } else {
        Toast.fail(msg || '收藏失败')
      }
    } catch (e) {
      Toast.fail('收藏失败')
      console.log('=====handleCollect error======', e)
    }
  }

  function toPostDetail() {
    navigate('/post/' + postDetail.id)
  }

  return (
    <YCard>
      <div className="flex flex-col items-start gap-2">
        <div className="flex gap-2">
          <UserAvatar user={postDetail.createBy} />
          <div className="flex flex-col">
            <UserName user={postDetail.createBy}></UserName>
            <YTime time={postDetail.createdAt}></YTime>
          </div>
        </div>
        <div className="w-full" onClick={toPostDetail}>
          <ExpandableContent content={postDetail.content} />
          <div className="w-full">
            <MediaList list={postDetail.medias} />
          </div>
        </div>
        <div className="w-full flex">
          <div
            className="flex flex-1 justify-center items-center gap-1"
            onClick={handleLike}
          >
            {postDetail.isLike ? (
              <GoodJob fontSize="14px" color="#18a058" />
            ) : (
              <GoodJobO fontSize="14px" />
            )}
            <span>{postDetail.likedByCount}</span>
          </div>
          <div
            className="flex flex-1 justify-center items-center gap-1"
            onClick={toPostDetail}
          >
            <CommentO fontSize="14px" />
            <span>{postDetail.commentsCount}</span>
          </div>
          <div
            className="flex flex-1 justify-center items-center gap-1"
            onClick={handleCollect}
          >
            {postDetail.isCollect ? (
              <Star fontSize="14px" color="#18a058" />
            ) : (
              <StarO fontSize="14px" />
            )}
            <span>{postDetail.collectedByCount}</span>
          </div>
        </div>
      </div>
    </YCard>
  )
}

// projects/blog-uni/components/post/post-item.vue
<template>
	<uni-card margin="5px" class="card">
		<view class="post-top">
			<UserAvatar :url="post.createBy.avatar" :size="42"></UserAvatar>
			<view class="item-user">
				<view class="user-name">{{ post.createBy.name }}</view>
				<YTime class="item-time" :time="post.createdAt"></YTime>
			</view>
		</view>
		<YExpandanleContent class="post-content" :content="post.content"></YExpandanleContent>
		<MediaList :list="post.medias"></MediaList>
		<view class="action-container">
			<view class="action-item" @click="handleLike">
				<uni-icons type="hand-up-filled" size="20" color="#18a058" v-if="post.isLike"></uni-icons>
				<uni-icons type="hand-up" size="20" color="#6B7280" v-else></uni-icons>
				<view class="action-num">
					{{ post.likedByCount }}
				</view>
			</view>
			<view class="action-item">
				<uni-icons type="chatbubble" size="20" color="#6B7280"></uni-icons>
				<view class="action-num">
					{{ post.commentsCount }}
				</view>
			</view>
			<view class="action-item" @click="handleCollect">
				<uni-icons type="star-filled" size="20" color="#18a058" v-if="post.isCollect"></uni-icons>
				<uni-icons type="star" size="20" color="#6B7280" v-else></uni-icons>
				<view class="action-num">
					{{ post.collectedByCount }}
				</view>
			</view>
		</view>
	</uni-card>
</template>

<script>
	import YImage from '@/components/y-image.vue'
	import YTime from '@/components/y-time.vue'
	import YExpandanleContent from '@/components/y-expandable-content.vue'
	import MediaList from '@/components/media/media-list.vue'
	import UserAvatar from '@/components/user/user-avatar.vue'
	import Http, {
		urls
	} from '@/http'

	export default {
		name: 'post-item',
		props: {
			post: Object
		},
		components: {
			YImage,
			YTime,
			YExpandanleContent,
			MediaList,
			UserAvatar,
		},
		data() {
			return {

			}
		},
		created() {
			// console.log('+++++++post-item created++++++++++', getCurrentPages())
		},
		methods: {
			async handleLike() {
				try {
					const {
						success,
						result,
						msg
					} = await Http.post(urls.blog_like, { isLike: this.post.isLike ? 0 : 1, id: this.post.id })
					if (success) {
						this.post.isLike = !this.post.isLike
						this.post.isLike ? this.post.likedByCount ++ : this.post.likedByCount --
					}
				} catch (e) {

				}
			},
			async handleCollect(){
				try {
					const {
						success,
						result,
						msg
					} = await Http.post(urls.blog_collect, { isCollect: this.post.isCollect ? 0 : 1, id: this.post.id })
					if (success) {
						this.post.isCollect = !this.post.isCollect
						this.post.isCollect ? this.post.collectedByCount ++ : this.post.collectedByCount --
					}
				} catch (e) {

				}
			}
		}
	}
</script>

<style lang="scss" scoped>
	.card {
		::v-deep .uni-card {
			padding: 0;
		}
	}

	.post-item {
		display: flex;
	}

	.post-top {
		display: flex;
		align-items: center;
		justify-content: flex-start;

		.item-user {
			margin-left: 20rpx;

			.user-name {
				font-size: 18px;
				font-weight: 600;
				color: #18a058;
			}

			.item-time {
				color: #6B7280;
			}
		}
	}

	.post-content {
		::v-deep{
			color: $uni-main-color;
		}
	}

	.action-container {
		display: flex;
		margin-top: 12px;

		.action-item {
			flex: 1;
			display: flex;
			align-items: center;
			justify-content: center;
			gap: 4px;

			.action-num {
				font-size: 18px;
			}
		}
	}
</style>
