// projects/blog-h5/src/components/post/post-list.tsx
import { Blog } from 'sys-types'
import AppendListWrapper from '@/components/append-list-wrapper'
import PostItem from '@/components/post/post-item'

interface Props {
  url?: string
  initParams?: any
}

export default function PostList({ url = '/blog/list', initParams }: Props) {
  const createItem = (post: Blog) => {
    return <PostItem post={post} key={post.id}></PostItem>
  }

  return (
    <div>
      <AppendListWrapper
        url={url}
        createItem={createItem}
        initParams={initParams}
      />
    </div>
  )
}

// projects/blog-uni/components/post/post-list.vue
<template>
	<view>
		<YAppendListWrapper #default="{pageItem: post}" :url="urls.blog_list">
			<PostItem :post="post"></PostItem>
		</YAppendListWrapper>
	</view>
</template>

<script>
	import PostItem from './post-item.vue'
	import YAppendListWrapper from '@/components/y-append-list-wrapper.vue'
	import Http, { urls } from '@/http'

	export default {
		name: "post-list",
		components: {
			YAppendListWrapper,
			PostItem,
		},
		data() {
			return {
				urls
			}
		},
		created() {
		},
		methods: {
		}
	}
</script>

<style>

</style>
